
export enum AppState {
  LOGIN = 'LOGIN',
  TRANSLATOR = 'TRANSLATOR'
}

export interface Message {
  id: string;
  sender: 'staff' | 'visitor';
  originalText: string;
  translatedText: string;
  timestamp: number;
}

export interface Language {
  code: string;
  name: string;
}

export const LANGUAGES: Language[] = [
  { code: 'auto', name: 'Autodetect' },
  { code: 'nl-BE', name: 'Flemish' },
  { code: 'ab-GE', name: 'Abkhaz' },
  { code: 'ace-ID', name: 'Acehnese' },
  { code: 'ach-UG', name: 'Acholi' },
  { code: 'aa-ET', name: 'Afar' },
  { code: 'af-ZA', name: 'Afrikaans' },
  { code: 'sq-AL', name: 'Albanian' },
  { code: 'alz-CD', name: 'Alur' },
  { code: 'am-ET', name: 'Amharic' },
  { code: 'ar-XA', name: 'Arabic' },
  { code: 'hy-AM', name: 'Armenian' },
  { code: 'as-IN', name: 'Assamese' },
  { code: 'av-RU', name: 'Avar' },
  { code: 'awa-IN', name: 'Awadhi' },
  { code: 'ay-BO', name: 'Aymara' },
  { code: 'az-AZ', name: 'Azerbaijani' },
  { code: 'ban-ID', name: 'Balinese' },
  { code: 'bal-PK', name: 'Baluchi' },
  { code: 'bm-ML', name: 'Bambara' },
  { code: 'bci-CI', name: 'Baoulé' },
  { code: 'ba-RU', name: 'Bashkir' },
  { code: 'eu-ES', name: 'Basque' },
  { code: 'btx-ID', name: 'Batak Karo' },
  { code: 'bts-ID', name: 'Batak Simalungun' },
  { code: 'bbc-ID', name: 'Batak Toba' },
  { code: 'be-BY', name: 'Belarusian' },
  { code: 'bem-ZM', name: 'Bemba' },
  { code: 'bn-BD', name: 'Bengali' },
  { code: 'bew-ID', name: 'Betawi' },
  { code: 'bho-IN', name: 'Bhojpuri' },
  { code: 'bik-PH', name: 'Bikol' },
  { code: 'bs-BA', name: 'Bosnian' },
  { code: 'br-FR', name: 'Breton' },
  { code: 'bg-BG', name: 'Bulgarian' },
  { code: 'bua-RU', name: 'Buryat' },
  { code: 'yue-HK', name: 'Cantonese' },
  { code: 'ca-ES', name: 'Catalan' },
  { code: 'ceb-PH', name: 'Cebuano' },
  { code: 'ch-GU', name: 'Chamorro' },
  { code: 'ce-RU', name: 'Chechen' },
  { code: 'ny-MW', name: 'Chichewa' },
  { code: 'zh-CN', name: 'Chinese (Simplified)' },
  { code: 'zh-TW', name: 'Chinese (Traditional)' },
  { code: 'chk-FM', name: 'Chuukese' },
  { code: 'cv-RU', name: 'Chuvash' },
  { code: 'co-FR', name: 'Corsican' },
  { code: 'crh-RU', name: 'Crimean Tatar' },
  { code: 'hr-HR', name: 'Croatian' },
  { code: 'cs-CZ', name: 'Czech' },
  { code: 'da-DK', name: 'Danish' },
  { code: 'prs-AF', name: 'Dari' },
  { code: 'dv-MV', name: 'Dhivehi' },
  { code: 'din-SS', name: 'Dinka' },
  { code: 'doi-IN', name: 'Dogri' },
  { code: 'nl-NL', name: 'Dutch' },
  { code: 'dyu-BF', name: 'Dyula' },
  { code: 'dz-BT', name: 'Dzongkha' },
  { code: 'en-US', name: 'English' },
  { code: 'eo-EU', name: 'Esperanto' },
  { code: 'et-EE', name: 'Estonian' },
  { code: 'ee-GH', name: 'Ewe' },
  { code: 'fo-FO', name: 'Faroese' },
  { code: 'fj-FJ', name: 'Fijian' },
  { code: 'fil-PH', name: 'Filipino' },
  { code: 'fi-FI', name: 'Finnish' },
  { code: 'fr-FR', name: 'French' },
  { code: 'fr-CA', name: 'French (Canada)' },
  { code: 'fy-NL', name: 'Frisian' },
  { code: 'ff-SN', name: 'Fulani' },
  { code: 'gl-ES', name: 'Galician' },
  { code: 'ka-GE', name: 'Georgian' },
  { code: 'de-DE', name: 'German' },
  { code: 'el-GR', name: 'Greek' },
  { code: 'gn-PY', name: 'Guarani' },
  { code: 'gu-IN', name: 'Gujarati' },
  { code: 'ht-HT', name: 'Haitian Creole' },
  { code: 'ha-NG', name: 'Hausa' },
  { code: 'he-IL', name: 'Hebrew' },
  { code: 'hi-IN', name: 'Hindi' },
  { code: 'hmn-CN', name: 'Hmong' },
  { code: 'hu-HU', name: 'Hungarian' },
  { code: 'is-IS', name: 'Icelandic' },
  { code: 'ig-NG', name: 'Igbo' },
  { code: 'id-ID', name: 'Indonesian' },
  { code: 'ga-IE', name: 'Irish' },
  { code: 'it-IT', name: 'Italian' },
  { code: 'ja-JP', name: 'Japanese' },
  { code: 'jv-ID', name: 'Javanese' },
  { code: 'kn-IN', name: 'Kannada' },
  { code: 'kk-KZ', name: 'Kazakh' },
  { code: 'km-KH', name: 'Khmer' },
  { code: 'rw-RW', name: 'Kinyarwanda' },
  { code: 'ko-KR', name: 'Korean' },
  { code: 'ku-TR', name: 'Kurdish (Kurmanji)' },
  { code: 'ckb-IQ', name: 'Kurdish (Sorani)' },
  { code: 'lo-LA', name: 'Lao' },
  { code: 'la-VA', name: 'Latin' },
  { code: 'lv-LV', name: 'Latvian' },
  { code: 'ln-CD', name: 'Lingala' },
  { code: 'lt-LT', name: 'Lithuanian' },
  { code: 'lg-UG', name: 'Luganda' },
  { code: 'mk-MK', name: 'Macedonian' },
  { code: 'mg-MG', name: 'Malagasy' },
  { code: 'ms-MY', name: 'Malay' },
  { code: 'ml-IN', name: 'Malayalam' },
  { code: 'mt-MT', name: 'Maltese' },
  { code: 'mi-NZ', name: 'Maori' },
  { code: 'mr-IN', name: 'Marathi' },
  { code: 'mn-MN', name: 'Mongolian' },
  { code: 'my-MM', name: 'Myanmar (Burmese)' },
  { code: 'ne-NP', name: 'Nepali' },
  { code: 'no-NO', name: 'Norwegian' },
  { code: 'or-IN', name: 'Odia (Oriya)' },
  { code: 'om-ET', name: 'Oromo' },
  { code: 'ps-AF', name: 'Pashto' },
  { code: 'fa-IR', name: 'Persian' },
  { code: 'pl-PL', name: 'Polish' },
  { code: 'pt-BR', name: 'Portuguese (Brazil)' },
  { code: 'pt-PT', name: 'Portuguese (Portugal)' },
  { code: 'pa-IN', name: 'Punjabi' },
  { code: 'qu-PE', name: 'Quechua' },
  { code: 'ro-RO', name: 'Romanian' },
  { code: 'ru-RU', name: 'Russian' },
  { code: 'sm-WS', name: 'Samoan' },
  { code: 'sa-IN', name: 'Sanskrit' },
  { code: 'gd-GB', name: 'Scots Gaelic' },
  { code: 'sr-RS', name: 'Serbian' },
  { code: 'st-LS', name: 'Sesotho' },
  { code: 'sn-ZW', name: 'Shona' },
  { code: 'sd-PK', name: 'Sindhi' },
  { code: 'si-LK', name: 'Sinhala' },
  { code: 'sk-SK', name: 'Slovak' },
  { code: 'sl-SI', name: 'Slovenian' },
  { code: 'so-SO', name: 'Somali' },
  { code: 'es-ES', name: 'Spanish' },
  { code: 'su-ID', name: 'Sundanese' },
  { code: 'sw-TZ', name: 'Swahili' },
  { code: 'sv-SE', name: 'Swedish' },
  { code: 'tg-TJ', name: 'Tajik' },
  { code: 'ta-IN', name: 'Tamil' },
  { code: 'tt-RU', name: 'Tatar' },
  { code: 'te-IN', name: 'Telugu' },
  { code: 'th-TH', name: 'Thai' },
  { code: 'bo-CN', name: 'Tibetan' },
  { code: 'ti-ET', name: 'Tigrinya' },
  { code: 'ts-ZA', name: 'Tsonga' },
  { code: 'tn-BW', name: 'Tswana' },
  { code: 'tr-TR', name: 'Turkish' },
  { code: 'tk-TM', name: 'Turkmen' },
  { code: 'uk-UA', name: 'Ukrainian' },
  { code: 'ur-PK', name: 'Urdu' },
  { code: 'ug-CN', name: 'Uyghur' },
  { code: 'uz-UZ', name: 'Uzbek' },
  { code: 'vi-VN', name: 'Vietnamese' },
  { code: 'cy-GB', name: 'Welsh' },
  { code: 'xh-ZA', name: 'Xhosa' },
  { code: 'yi-IL', name: 'Yiddish' },
  { code: 'yo-NG', name: 'Yoruba' },
  { code: 'zu-ZA', name: 'Zulu' }
];
